In [108]:
import pandas as pd
import numpy as np

### Загрузка обработанных данных

In [109]:
cian = pd.read_excel('Cian Москва и Область.xlsx')
d_mos = pd.read_excel('domclick_mos.xlsx')
d_obl = pd.read_excel('domclick_oblast.xlsx')
price_cian = pd.read_excel('price-cian.xlsx')
secondary = pd.read_excel('secondary.xlsx')

# Просмотр обработанных данных

### cian

In [110]:
columns = ['Цена', 'Станция метро', 'Минут до метро', 'Адрес', 'Количество комнат',
           'Площадь', 'Жилая площадь', 'Кухня площадь', 'Этаж', 'Тип продажи',
           'Дом', 'Всего этажей', 'Лифт', 'Ремонт', 'Парковка',
           'Окна', 'Санузел', 'Высота потолков, м', 'Ссылка на объявление']

cian = cian[columns]

In [111]:
print(cian.shape)
cian.head(3)

(4556, 19)

,Цена,Станция метро,Минут до метро,Адрес,Количество комнат,Площадь,Жилая площадь,Кухня площадь,Этаж,Тип продажи,Дом,Всего этажей,Лифт,Ремонт,Парковка,Окна,Санузел,"Высота потолков, м",Ссылка на объявление
0,6300000,м. Опалиха,6.0,"Московская область, Красногорский район, Красн...",1,30.6,11.1,8.5,25,Свободная продажа,Монолитный,25,есть,Косметический,наземная,Во двор,Раздельный,NaN,https://www.cian.ru/sale/flat/289238903
1,6850000,NaN,NaN,"Московская область, Красногорский район, Красн...",1,35.6,18.0,7.0,16,Свободная продажа,Монолитный,26,есть,Без ремонта,NaN,NaN,NaN,NaN,https://www.cian.ru/sale/flat/274781081
2,9000000,м. Павшино,2.0,"Московская область, Красногорский район, Красн...",1,49.2,20.0,10.0,6,Свободная продажа,Кирпичный,15,есть,Евроремонт,NaN,NaN,Совмещенный,2.9,https://www.cian.ru/sale/flat/292849723

### d_mos

In [112]:
print(d_mos.shape)
d_mos.head(3)

(9897, 20)

,Цена,Метро,Минут до метро,Адрес,Комнат,Площадь,Жилая,Кухня,Этаж,Тип сделки,Год постройки,Материал стен,Серия дома,Количество этажей,Лифт,Тип перекрытий,Ремонт,Количество информации в объявлении,Количество указанной инфраструктуры,Ссылка
0,11000000,Некрасовка,17,Москва улица Лавриненко 3А,1,37.5,19.0,8.0,3,Свободная продажа,2018.0,Иные,П-44Т,17.0,есть,Железобетонный,NaN,14,2,https://domclick.ru/card/sale__flat__1866393858
1,4650000,NaN,NaN,Москва посёлок Рогово Юбилейная улица 12к2,1,38.0,18.0,9.0,5,Свободная продажа,2019.0,Кирпичный,NaN,5.0,NaN,Железобетонный,косметический,14,2,https://domclick.ru/card/sale__flat__1691896126
2,10800000,"Прокшино, Филатов Луг","13,45",Москва поселение Сосенское Прокшинский проспект 9,1,33.8,15.2,12.0,15,Свободная продажа,2022.0,Монолитно-кирпичный,NaN,18.0,NaN,Железобетонный,Отсутствует,13,1,https://domclick.ru/card/sale__flat__1691935139

### d_obl

In [113]:
columns = ['Цена', 'Адрес', 'Комнат', 'Площадь', 'Жилая', 'Кухня',
           'Этаж', 'Год постройки', 'Материал стен', 'Серия дома', 'Количество этажей',
           'Лифт', 'Тип перекрытий', 'Ремонт', 'Тип сделки', 'Количество информации в объявлении',
           'Ссылка']

d_obl = d_obl[columns]

In [114]:
print(d_obl.shape)
d_obl.head(3)

(6375, 17)

,Цена,Адрес,Комнат,Площадь,Жилая,Кухня,Этаж,Год постройки,Материал стен,Серия дома,Количество этажей,Лифт,Тип перекрытий,Ремонт,Тип сделки,Количество информации в объявлении,Ссылка
0,4300000,Московская область городской округ Люберцы раб...,1,30.4,NaN,8.0,2,1972.0,Кирпичный,v-кирпичный,5.0,NaN,Железобетонный,NaN,NaN,12,https://domclick.ru/card/sale__flat__1894676156
1,5800000,Московская область Лобня Научный городок 3,1,31.2,NaN,7.3,8,1978.0,Кирпичный,v-кирпичный,9.0,есть,Железобетонный,NaN,NaN,12,https://domclick.ru/card/sale__flat__1885409722
2,6750000,Московская область Ленинский городской округ д...,1,44.0,17.0,9.0,2,2015.0,Монолитный,II-01,17.0,есть,Железобетонный,Евро,Свободная продажа,14,https://domclick.ru/card/sale__flat__1714472790

### price_cian

In [115]:
columns = ['Цена', 'Метро', 'Метро время', 'Регион', 'Город', 'Городской округ', 'Улица',
           'Номер дома', 'Число комнат', 'Площадь общая', 'Площадь жилая', 'Площадь кухни', 'Этаж', 'Тип договора',
           'Отделка', 'Тип квартиры', 'Номер на этаже', 'Тип помещения', 'Ссылка']

price_cian = price_cian[columns]

In [116]:
print(price_cian.shape)
price_cian.head(3)

(9885, 19)

,Цена,Метро,Метро время,Регион,Город,Городской округ,Улица,Номер дома,Число комнат,Площадь общая,Площадь жилая,Площадь кухни,Этаж,Тип договора,Отделка,Тип квартиры,Номер на этаже,Тип помещения,Ссылка
0,8536067.0,Домодедовская,8.0,Московская,Ленинский,NaN,Миниполис Дивное ЖК,к16,2.0,56.45,27.1,14.2,1,свободная продажа,NaN,Новостройка,5.0,2-56,https://www.cian.ru/sale/flat/248144206/
1,NaN,Депо,17.0,Москва,Москва,Москва,Люблинская,NaN,1.0,44.43,13.9,18.2,3,дду,NaN,Новостройка,2.0,1-44.43,https://www.cian.ru/sale/flat/248154196/
2,NaN,Депо,17.0,Москва,Москва,Москва,Люблинская,NaN,1.0,44.43,13.9,18.2,7,дду,NaN,Новостройка,2.0,1-44.43,https://www.cian.ru/sale/flat/248154209/

### secondary

In [117]:
columns =   ['Цена', 'Тип квартиры', 'Адрес', 'Регион', 'Город',
             'Район', 'Уникальный номер адреса', 'Уникальный номер корпуса', 'Число комнат', 'Площадь общая',
             'Площадь жидая', 'Площадь кухни', 'Тип дома', 'Тип стен дома', 'Этаж', 'Номер этажа',
             'Плащадь квартир', 'Всего этажей', 'Год постройки', 'Тип договора', 'Тип ремонта', 'Ссылка']

secondary = secondary[columns]

In [118]:
print(secondary.shape)
secondary.head(3)

(4062, 22)

,Цена,Тип квартиры,Адрес,Регион,Город,Район,Уникальный номер адреса,Уникальный номер корпуса,Число комнат,Площадь общая,...,Тип дома,Тип стен дома,Этаж,Номер этажа,Плащадь квартир,Всего этажей,Год постройки,Тип договора,Тип ремонта,Ссылка
0,10750000,Вторичное,"Россия, Московская область, Котельники, улица ...",Московская,Котельники,Люберецкий,NaN,Квартиры,3.0,116.9,...,NaN,NaN,NaN,2,44855.0,23.0,NaN,свободная продажа,требуется ремонт,https://cian.ru/sale/flat/248058617
1,16000000,Вторичное,"Московская область, Ленинский район, Суханово ...",Московская,NaN,Ленинский,NaN,NaN,5.0,127.0,...,NaN,NaN,NaN,4,NaN,NaN,NaN,свободная продажа,NaN,https://cian.ru/sale/flat/248110937
2,12300000,Вторичное,"Московская область, Котельники городской округ...",Московская,Котельники,Люберецкий,NaN,Квартиры,3.0,108.0,...,NaN,NaN,NaN,9,44855.0,23.0,NaN,свободная продажа,евроремонт,https://cian.ru/sale/flat/248155168

# Функция объединения

In [119]:
def inner_data(cian,d_mos,d_obl,price_cian,secondary):
    
    # Объединяем cian и d_mos
    
    cian.columns = ['Цена', 
                'Станция метро', 
                'Минут до метро', 
                'Адрес', 
                'Количество комнат',
                'Площадь', 
                'Жилая площадь', 
                'Кухня площадь', 
                'Этаж', 
                'Тип сделки',
                'Материал стен', 
                'Количество этажей', 
                'Лифт', 
                'Ремонт', 
                'Парковка', 
                'Окна', 
                'Санузел',
                'Высота потолков', 
                'Ссылка']
    d_mos.columns = ['Цена', 
                     'Станция метро', 
                     'Минут до метро', 
                     'Адрес', 
                     'Количество комнат',
                     'Площадь',
                     'Жилая площадь', 
                     'Кухня площадь',
                     'Этаж', 
                     'Тип сделки', 
                     'Год постройки',
                     'Материал стен', 
                     'Серия дома', 
                     'Количество этажей', 
                     'Лифт', 
                     'Тип перекрытий', 
                     'Ремонт', 
                     'Количество информации в объявлении',
                     'Количество указанной инфраструктуры', 
                     'Ссылка']
    cian['Станция метро'] = cian[cian['Станция метро'].notna()]['Станция метро'].apply(lambda x: x.replace('м.', ''))
    # Оставляем только станцию и кратчайший путь
    
    d_mos['Станция метро'] = d_mos[d_mos['Станция метро'].notna()]['Станция метро'].apply(lambda x: str(x).split(',')[0])
    d_mos['Минут до метро'] = d_mos[d_mos['Минут до метро'].notna()]['Минут до метро'].apply(lambda x: str(x).split(',')[0])
    d_mos['Минут до метро'] = d_mos[d_mos['Минут до метро'].notna()]['Минут до метро'].apply(lambda x: str(x)\
                                                                                         .replace('часа','')\
                                                                                         .replace('час',''))
    # Меняем тип данных
    d_mos['Минут до метро'] = d_mos['Минут до метро'].astype('float')
    
    # Объединяем
    df = pd.concat([cian, d_mos])
    
    # d_obl
    d_obl.columns = ['Цена', 
                 'Адрес', 
                 'Количество комнат', 
                 'Площадь', 
                 'Жилая площадь', 
                 'Кухня площадь', 
                 'Этаж',
                 'Тип сделки',
                 'Год постройки', 
                 'Материал стен', 
                 'Серия дома', 
                 'Количество этажей',
                 'Лифт', 
                 'Тип перекрытий', 
                 'Ремонт',
                 'Количество информации в объявлении', 
                 'Ссылка']
    df = pd.concat([df, d_obl])
    
    # price_cian
    price_cian.drop('Городской округ', axis = 1, inplace = True)
    
    # Создаем столбец Адрес
    columns = ['Город', 'Улица']

    for i in columns: 
        price_cian[i] = price_cian[i].fillna('нет')

    price_cian['Номер дома'] = price_cian['Номер дома'].fillna('.')
    adres = price_cian['Регион'] + [', '] + price_cian['Город']+ [', '] + price_cian['Улица']+ [', '] + price_cian['Номер дома']
    price_cian.insert(3, 'Адрес', adres)
    
    price_cian.drop(['Регион', 'Город', 'Улица', 'Номер дома'], axis = 1, inplace = True)
    price_cian['Адрес'] = price_cian['Адрес'].apply(lambda x: x.replace('нет','').replace(', .',''))
    
    price_cian.columns =['Цена',
                     'Станция метро',
                     'Минут до метро',
                     'Адрес',
                     'Количество комнат',
                     'Площадь',
                     'Жилая площадь',
                     'Кухня площадь',
                     'Этаж',
                     'Тип сделки',
                     'Отделка',
                     'Тип квартиры',
                     'Номер на этаже',
                     'Тип помещения',
                     'Ссылка']
    df = pd.concat([df, price_cian])
    
    # secondary
    secondary.drop(['Регион', 'Город', 'Район','Уникальный номер адреса', 'Уникальный номер корпуса'], axis = 1, inplace = True)
    secondary.drop(['Тип дома', 'Тип стен дома', 'Этаж','Год постройки'], axis = 1, inplace = True)
    
    secondary.columns = ['Цена', 
                     'Тип квартиры',
                     'Адрес', 
                     'Количество комнат',
                     'Площадь', 
                     'Жилая площадь', 
                     'Кухня площадь', 
                     'Номер на этаже', 
                     'Площадь квартир',
                     'Количество этажей',
                     'Тип договора',
                     'Ремонт',
                     'Ссылка']
    df = pd.concat([df, secondary])
    
    df['Тип квартиры'] = df['Тип квартиры'].fillna('Вторичное')
    return df

In [120]:
df = inner_data(cian,d_mos,d_obl,price_cian,secondary)
print(df.shape)
df.head()

(34775, 30)

,Цена,Станция метро,Минут до метро,Адрес,Количество комнат,Площадь,Жилая площадь,Кухня площадь,Этаж,Тип сделки,...,Серия дома,Тип перекрытий,Количество информации в объявлении,Количество указанной инфраструктуры,Отделка,Тип квартиры,Номер на этаже,Тип помещения,Площадь квартир,Тип договора
0,6300000.0,Опалиха,6.0,"Московская область, Красногорский район, Красн...",1.0,30.6,11.1,8.5,25.0,Свободная продажа,...,NaN,NaN,NaN,NaN,NaN,Вторичное,NaN,NaN,NaN,NaN
1,6850000.0,NaN,NaN,"Московская область, Красногорский район, Красн...",1.0,35.6,18.0,7.0,16.0,Свободная продажа,...,NaN,NaN,NaN,NaN,NaN,Вторичное,NaN,NaN,NaN,NaN
2,9000000.0,Павшино,2.0,"Московская область, Красногорский район, Красн...",1.0,49.2,20.0,10.0,6.0,Свободная продажа,...,NaN,NaN,NaN,NaN,NaN,Вторичное,NaN,NaN,NaN,NaN
3,11090000.0,Мякинино,14.0,"Московская область, Красногорский район, Красн...",1.0,44.7,16.2,13.1,10.0,Свободная продажа,...,NaN,NaN,NaN,NaN,NaN,Вторичное,NaN,NaN,NaN,NaN
4,8300000.0,Строгино,8.0,"Московская область, Красногорский район, Красн...",1.0,35.1,16.0,11.0,12.0,Свободная продажа,...,NaN,NaN,NaN,NaN,NaN,Вторичное,NaN,NaN,NaN,NaN

In [129]:
data = round((df.isna().sum() / df.shape[0]) * 100, 2).to_frame()
data.columns = ['NaN%']
columns = list(data[data['NaN%'] < 55].index)

df = df[columns]

In [131]:
print(df.shape)
df.head()

(34775, 18)

,Цена,Станция метро,Минут до метро,Адрес,Количество комнат,Площадь,Жилая площадь,Кухня площадь,Этаж,Тип сделки,Материал стен,Количество этажей,Лифт,Ремонт,Ссылка,Год постройки,Количество информации в объявлении,Тип квартиры
0,6300000.0,Опалиха,6.0,"Московская область, Красногорский район, Красн...",1.0,30.6,11.1,8.5,25.0,Свободная продажа,Монолитный,25.0,есть,Косметический,https://www.cian.ru/sale/flat/289238903,NaN,NaN,Вторичное
1,6850000.0,NaN,NaN,"Московская область, Красногорский район, Красн...",1.0,35.6,18.0,7.0,16.0,Свободная продажа,Монолитный,26.0,есть,Без ремонта,https://www.cian.ru/sale/flat/274781081,NaN,NaN,Вторичное
2,9000000.0,Павшино,2.0,"Московская область, Красногорский район, Красн...",1.0,49.2,20.0,10.0,6.0,Свободная продажа,Кирпичный,15.0,есть,Евроремонт,https://www.cian.ru/sale/flat/292849723,NaN,NaN,Вторичное
3,11090000.0,Мякинино,14.0,"Московская область, Красногорский район, Красн...",1.0,44.7,16.2,13.1,10.0,Свободная продажа,Панельный,25.0,есть,Косметический,https://www.cian.ru/sale/flat/290714580,NaN,NaN,Вторичное
4,8300000.0,Строгино,8.0,"Московская область, Красногорский район, Красн...",1.0,35.1,16.0,11.0,12.0,Свободная продажа,Монолитный,33.0,есть,Евроремонт,https://www.cian.ru/sale/flat/293556306,NaN,NaN,Вторичное

# Сохраняем набор данных

In [132]:
df.to_excel('Цены на недвижимость.xlsx', index = False)